#!/usr/bin/env python3
"""Load graph edge tables from PostgreSQL to Fabric Lakehouse via OneLake.

Reads edges from demo.ops_graph_edges (built by 14_build_graph_edges.py),
splits into per-edge-type Delta tables for Fabric Graph ingestion,
and writes a combined graph_edges_all table for KQL fallback.

Usage:
    python scripts/19_load_graph_to_lakehouse.py
    python scripts/19_load_graph_to_lakehouse.py --pg-host $PGHOST
    python scripts/19_load_graph_to_lakehouse.py --from-csv data/enriched_graph_edges.csv
"""

from __future__ import annotations

import argparse
import csv
import os
import subprocess
import sys
from collections import defaultdict
from typing import Dict, List, Tuple

import pyarrow as pa
from deltalake import write_deltalake

# ---------------------------------------------------------------------------
# Constants (same as 18_load_lakehouse_direct.py)
# ---------------------------------------------------------------------------
WS_ID = "cfbb82a5-799e-421b-b2cc-8a164b17a849"
LH_ID = "de9e3323-0952-479e-a6ea-0de93c2d4f95"
ONELAKE_BASE = f"abfss://{WS_ID}@onelake.dfs.fabric.microsoft.com/{LH_ID}/Tables"

# Edge type -> Lakehouse table name mapping
EDGE_TYPE_TABLE_MAP: Dict[str, str] = {
    "HAS_RUNWAY": "edge_has_runway",
    "SERVED_BY_ROUTE": "edge_served_by_route",
    "OPERATED_BY": "edge_operated_by",
    "CONNECTS": "edge_connects",
    "SAME_CITY": "edge_same_city",
    "DEPARTS": "edge_departs",
    "ARRIVES": "edge_arrives",
    "OPERATES": "edge_operates",
    "CREWED_BY": "edge_crewed_by",
    "MEL_ON": "edge_mel_on",
    "HAS_NAVAID": "edge_has_navaid",
    "HAS_FREQUENCY": "edge_has_frequency",
    "AFFECTS": "edge_affects",
    "AFFECTS_RUNWAY": "edge_affects_runway",
    "REPORTED_AT": "edge_reported_at",
    "FLOWN_BY": "edge_flown_by",
}

EDGE_SCHEMA = pa.schema([
    ("src_type", pa.string()),
    ("src_id", pa.string()),
    ("edge_type", pa.string()),
    ("dst_type", pa.string()),
    ("dst_id", pa.string()),
])


def get_token() -> str:
    """Get Azure AD token for OneLake (storage.azure.com)."""
    result = subprocess.run(
        ["az", "account", "get-access-token", "--resource", "https://storage.azure.com",
         "--query", "accessToken", "-o", "tsv"],
        capture_output=True, text=True,
    )
    return result.stdout.strip()


def storage_opts(token: str) -> Dict[str, str]:
    """Storage options for deltalake OneLake access."""
    return {
        "bearer_token": token,
        "use_fabric_endpoint": "true",
    }


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

EdgeRow = Tuple[str, str, str, str, str]  # (src_type, src_id, edge_type, dst_type, dst_id)


def load_edges_from_pg(args) -> List[EdgeRow]:
    """Read all edges from demo.ops_graph_edges in PostgreSQL."""
    import psycopg2

    host = args.pg_host or os.getenv("PGHOST", "")
    port = args.pg_port or os.getenv("PGPORT", "5432")
    db = args.pg_db or os.getenv("PGDATABASE", "aviationrag")
    user = args.pg_user or os.getenv("PGUSER", "")
    password = args.pg_password or os.getenv("PGPASSWORD", "")
    schema = args.schema

    if not all([host, user, password]):
        print("ERROR: PGHOST, PGUSER, and PGPASSWORD are required for PG mode")
        sys.exit(1)

    print(f"  Connecting to {host}:{port}/{db} (schema: {schema})...")
    conn = psycopg2.connect(
        host=host,
        port=int(port),
        database=db,
        user=user,
        password=password,
        sslmode="require",
        connect_timeout=10,
    )
    cur = conn.cursor()

    cur.execute(f'SELECT COUNT(*) FROM "{schema}".ops_graph_edges')
    total = cur.fetchone()[0]
    print(f"  Total edges in PG: {total:,}")

    if total == 0:
        print("  WARNING: No edges found. Run scripts/14_build_graph_edges.py first.")
        cur.close()
        conn.close()
        return []

    cur.execute(
        f'SELECT src_type, src_id, edge_type, dst_type, dst_id FROM "{schema}".ops_graph_edges'
    )
    rows = cur.fetchall()
    cur.close()
    conn.close()
    return rows


def load_edges_from_csv(csv_path: str) -> List[EdgeRow]:
    """Read edges from a CSV export (generated by 14_build_graph_edges.py --export-csv)."""
    print(f"  Reading CSV: {csv_path}")
    rows: List[EdgeRow] = []
    with open(csv_path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for r in reader:
            rows.append((
                r["src_type"],
                r["src_id"],
                r["edge_type"],
                r["dst_type"],
                r["dst_id"],
            ))
    return rows


def split_by_edge_type(rows: List[EdgeRow]) -> Dict[str, List[EdgeRow]]:
    """Group edges by edge_type."""
    groups: Dict[str, List[EdgeRow]] = defaultdict(list)
    for row in rows:
        groups[row[2]].append(row)
    return dict(groups)


def rows_to_arrow(rows: List[EdgeRow]) -> pa.Table:
    """Convert edge rows to a PyArrow table."""
    return pa.table({
        "src_type": [r[0] for r in rows],
        "src_id": [r[1] for r in rows],
        "edge_type": [r[2] for r in rows],
        "dst_type": [r[3] for r in rows],
        "dst_id": [r[4] for r in rows],
    }, schema=EDGE_SCHEMA)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description="Load graph edges to Fabric Lakehouse")
    parser.add_argument("--from-csv", type=str, default=None,
                        help="Read edges from CSV instead of PostgreSQL")
    parser.add_argument("--pg-host", default="")
    parser.add_argument("--pg-port", default="5432")
    parser.add_argument("--pg-db", default="aviationrag")
    parser.add_argument("--pg-user", default="")
    parser.add_argument("--pg-password", default="")
    parser.add_argument("--schema", default="demo")
    parser.add_argument("--dry-run", action="store_true",
                        help="Show what would be written without writing")
    args = parser.parse_args()

    print("=== Graph Edge Lakehouse Loader ===")
    print(f"OneLake base: {ONELAKE_BASE}")
    print()

    # Load edges
    if args.from_csv:
        all_edges = load_edges_from_csv(args.from_csv)
    else:
        print("Loading edges from PostgreSQL...")
        all_edges = load_edges_from_pg(args)

    if not all_edges:
        print("\nNo edges to load. Exiting.")
        sys.exit(1)

    print(f"\nTotal edges loaded: {len(all_edges):,}")

    # Split by edge type
    groups = split_by_edge_type(all_edges)
    print(f"Edge types found: {len(groups)}")
    for etype, rows in sorted(groups.items(), key=lambda x: -len(x[1])):
        table_name = EDGE_TYPE_TABLE_MAP.get(etype, f"edge_{etype.lower()}")
        print(f"  {etype:25s} -> {table_name:30s} ({len(rows):,} rows)")

    if args.dry_run:
        print("\n[DRY RUN] No data written.")
        return

    # Get OneLake token
    token = get_token()
    if not token:
        print("ERROR: Could not get Azure token for OneLake")
        sys.exit(1)
    print(f"\nToken acquired ({len(token)} chars)")

    opts = storage_opts(token)
    results: Dict[str, Tuple[str, object]] = {}

    # Write per-edge-type tables
    for etype, rows in sorted(groups.items()):
        table_name = EDGE_TYPE_TABLE_MAP.get(etype, f"edge_{etype.lower()}")
        target = f"{ONELAKE_BASE}/{table_name}"
        print(f"\n--- {table_name} ({etype}, {len(rows):,} rows) ---")
        try:
            arrow_table = rows_to_arrow(rows)
            print(f"  Writing to: {target}")
            write_deltalake(target, arrow_table, mode="overwrite", storage_options=opts)
            print(f"  OK: {table_name}")
            results[table_name] = ("OK", len(rows))
        except Exception as e:
            print(f"  FAILED: {e}")
            results[table_name] = ("FAIL", str(e))

    # Write combined table
    combined_name = "graph_edges_all"
    combined_target = f"{ONELAKE_BASE}/{combined_name}"
    print(f"\n--- {combined_name} (ALL, {len(all_edges):,} rows) ---")
    try:
        arrow_table = rows_to_arrow(all_edges)
        print(f"  Writing to: {combined_target}")
        write_deltalake(combined_target, arrow_table, mode="overwrite", storage_options=opts)
        print(f"  OK: {combined_name}")
        results[combined_name] = ("OK", len(all_edges))
    except Exception as e:
        print(f"  FAILED: {e}")
        results[combined_name] = ("FAIL", str(e))

    # Summary
    print(f"\n{'='*60}")
    print("SUMMARY")
    print(f"{'='*60}")
    ok_count = 0
    fail_count = 0
    for name, (status, detail) in sorted(results.items()):
        if status == "OK":
            print(f"  {name:30s}  {status}  {detail:,} rows")
            ok_count += 1
        else:
            print(f"  {name:30s}  {status}  {detail}")
            fail_count += 1
    print(f"\n  Total: {ok_count} OK, {fail_count} FAIL out of {len(results)} tables")


if __name__ == "__main__":
    main()
