#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
K8S_DIR="${K8S_DIR:-${SCRIPT_DIR}/../k8s}"
OUT_DIR="${1:-/tmp/k8s-rendered}"

TARGET_ACCOUNT_UPN="admin@MngEnvMCAP705508.onmicrosoft.com"
TARGET_TENANT_ID="52095a81-130f-4b06-83f1-9859b2c73de6"
TARGET_SUBSCRIPTION_ID="6a539906-6ce2-4e3b-84ee-89f701de18d8"

# Defaults for non-secret values.
: "${AZURE_OPENAI_API_VERSION:=2024-10-21}"
: "${AZURE_OPENAI_DEPLOYMENT_NAME:=gpt-5-nano}"
: "${AZURE_OPENAI_WORKER_DEPLOYMENT_NAME:=${AZURE_OPENAI_DEPLOYMENT_NAME}}"
: "${AZURE_OPENAI_ORCHESTRATOR_DEPLOYMENT_NAME:=gpt-5-nano}"
: "${AZURE_OPENAI_REASONING_DEPLOYMENT_NAME:=gpt-5-mini}"
: "${AZURE_REASONING_OPENAI_API_VERSION:=v1}"
: "${AZURE_OPENAI_PROJECT_ENDPOINT:=}"
: "${AZURE_FOUNDRY_PROJECT_ENDPOINT:=${AZURE_OPENAI_PROJECT_ENDPOINT}}"
: "${AZURE_TEXT_EMBEDDING_DEPLOYMENT_NAME:=text-embedding-3-small}"
: "${K8S_NAMESPACE:=aviation-rag}"
: "${PGPORT:=5432}"
: "${PGDATABASE:=aviationrag}"
: "${PGUSER:=aviationrag_readonly}"
: "${FLASK_ENV:=production}"
: "${LOG_LEVEL:=INFO}"
: "${SCHEMA_CACHE_TTL_SECONDS:=300}"
: "${KQL_SCHEMA_MODE:=static}"
: "${OTEL_SERVICE_NAME:=aviation-rag-backend}"
: "${ENVIRONMENT:=production}"
: "${AF_SESSION_TTL_SECONDS:=3600}"
: "${AF_MAX_SESSIONS:=500}"
: "${AZURE_OPENAI_TIMEOUT_SECONDS:=45}"
: "${AZURE_OPENAI_MAX_RETRIES:=1}"
: "${GUNICORN_WORKER_CLASS:=gthread}"
: "${GUNICORN_WORKERS:=1}"
: "${GUNICORN_THREADS:=4}"
: "${GUNICORN_TIMEOUT_SECONDS:=240}"
: "${GUNICORN_GRACEFUL_TIMEOUT_SECONDS:=30}"
: "${GUNICORN_KEEPALIVE_SECONDS:=5}"
: "${GUNICORN_MAX_REQUESTS:=1000}"
: "${GUNICORN_MAX_REQUESTS_JITTER:=200}"
: "${FABRIC_KQL_ENDPOINT:=}"
: "${FABRIC_KUSTO_CLUSTER_URL:=}"
: "${FABRIC_KQL_DATABASE:=}"
: "${FABRIC_GRAPH_ENDPOINT:=}"
: "${FABRIC_NOSQL_ENDPOINT:=}"
: "${FABRIC_GRAPH_DATABASE:=}"
: "${ALLOW_SHARED_FABRIC_ENDPOINTS:=false}"
: "${ALLOW_STATIC_FABRIC_BEARER:=false}"
: "${FABRIC_TOKEN_MIN_TTL_SECONDS:=120}"
: "${GRAPH_TIMEOUT_SECONDS:=3}"
: "${GRAPH_MAX_RETRIES:=1}"
: "${GRAPH_RETRY_BACKOFF_SECONDS:=0.25}"
: "${GRAPH_CIRCUIT_BREAKER_FAIL_THRESHOLD:=3}"
: "${GRAPH_CIRCUIT_BREAKER_OPEN_SECONDS:=30}"
: "${FABRIC_SQL_ENDPOINT:=}"
: "${FABRIC_SQL_SERVER:=}"
: "${FABRIC_SQL_DATABASE:=}"
: "${FABRIC_SQL_MODE:=auto}"
: "${AZURE_COSMOS_ENDPOINT:=}"
: "${AZURE_COSMOS_DATABASE:=aviationrag}"
: "${AZURE_COSMOS_CONTAINER:=notams}"
: "${BACKEND_INGRESS_HOST:=aviation-rag-api.westeurope.cloudapp.azure.com}"
: "${ALLOWED_ORIGIN:=https://aviation-rag-frontend-705508.azurewebsites.net}"
: "${IMAGE_TAG:=latest}"
: "${EXPECTED_RUNTIME_ACCOUNT_UPN:=${TARGET_ACCOUNT_UPN}}"
: "${EXPECTED_RUNTIME_TENANT_ID:=${TARGET_TENANT_ID}}"
: "${EXPECTED_RUNTIME_SUBSCRIPTION_ID:=${TARGET_SUBSCRIPTION_ID}}"
: "${AZURE_ACCOUNT_UPN:=${TARGET_ACCOUNT_UPN}}"
: "${AZURE_TENANT_ID:=${TARGET_TENANT_ID}}"
: "${AZURE_SUBSCRIPTION_ID:=${TARGET_SUBSCRIPTION_ID}}"

export AZURE_CONTAINER_REGISTRY IMAGE_NAME IMAGE_TAG
export AZURE_OPENAI_ENDPOINT AZURE_OPENAI_API_VERSION AZURE_OPENAI_DEPLOYMENT_NAME
export AZURE_OPENAI_WORKER_DEPLOYMENT_NAME AZURE_OPENAI_ORCHESTRATOR_DEPLOYMENT_NAME
export AZURE_OPENAI_REASONING_DEPLOYMENT_NAME
export AZURE_REASONING_OPENAI_API_VERSION AZURE_OPENAI_PROJECT_ENDPOINT AZURE_FOUNDRY_PROJECT_ENDPOINT
export AZURE_TEXT_EMBEDDING_DEPLOYMENT_NAME
export AZURE_OPENAI_TIMEOUT_SECONDS AZURE_OPENAI_MAX_RETRIES
export AZURE_SEARCH_ENDPOINT
export PII_ENDPOINT PII_CONTAINER_ENDPOINT
export K8S_NAMESPACE
export PGHOST PGPORT PGDATABASE PGUSER
export FLASK_ENV LOG_LEVEL
export SCHEMA_CACHE_TTL_SECONDS KQL_SCHEMA_MODE OTEL_SERVICE_NAME ENVIRONMENT AF_SESSION_TTL_SECONDS AF_MAX_SESSIONS
export GUNICORN_WORKER_CLASS GUNICORN_WORKERS GUNICORN_THREADS
export GUNICORN_TIMEOUT_SECONDS GUNICORN_GRACEFUL_TIMEOUT_SECONDS
export GUNICORN_KEEPALIVE_SECONDS GUNICORN_MAX_REQUESTS GUNICORN_MAX_REQUESTS_JITTER
export FABRIC_KQL_ENDPOINT FABRIC_KUSTO_CLUSTER_URL FABRIC_KQL_DATABASE FABRIC_GRAPH_ENDPOINT FABRIC_NOSQL_ENDPOINT
export FABRIC_GRAPH_DATABASE GRAPH_TIMEOUT_SECONDS GRAPH_MAX_RETRIES
export GRAPH_RETRY_BACKOFF_SECONDS GRAPH_CIRCUIT_BREAKER_FAIL_THRESHOLD GRAPH_CIRCUIT_BREAKER_OPEN_SECONDS
export ALLOW_SHARED_FABRIC_ENDPOINTS ALLOW_STATIC_FABRIC_BEARER FABRIC_TOKEN_MIN_TTL_SECONDS
export FABRIC_SQL_ENDPOINT FABRIC_SQL_SERVER FABRIC_SQL_DATABASE FABRIC_SQL_MODE
export AZURE_COSMOS_ENDPOINT AZURE_COSMOS_DATABASE AZURE_COSMOS_CONTAINER
export BACKEND_INGRESS_HOST ALLOWED_ORIGIN
export EXPECTED_RUNTIME_ACCOUNT_UPN EXPECTED_RUNTIME_TENANT_ID EXPECTED_RUNTIME_SUBSCRIPTION_ID
export AZURE_ACCOUNT_UPN AZURE_TENANT_ID AZURE_SUBSCRIPTION_ID

if [ -z "${EXPECTED_RUNTIME_ACCOUNT_UPN}" ] || [ -z "${EXPECTED_RUNTIME_TENANT_ID}" ] || [ -z "${EXPECTED_RUNTIME_SUBSCRIPTION_ID}" ]; then
  echo "Missing required runtime guardrail values (EXPECTED_RUNTIME_ACCOUNT_UPN / EXPECTED_RUNTIME_TENANT_ID / EXPECTED_RUNTIME_SUBSCRIPTION_ID)." >&2
  exit 1
fi

if [ "${EXPECTED_RUNTIME_ACCOUNT_UPN}" != "${TARGET_ACCOUNT_UPN}" ]; then
  echo "Out-of-policy EXPECTED_RUNTIME_ACCOUNT_UPN='${EXPECTED_RUNTIME_ACCOUNT_UPN}'. Expected '${TARGET_ACCOUNT_UPN}'." >&2
  exit 1
fi

if [ "${EXPECTED_RUNTIME_TENANT_ID}" != "${TARGET_TENANT_ID}" ]; then
  echo "Out-of-policy EXPECTED_RUNTIME_TENANT_ID='${EXPECTED_RUNTIME_TENANT_ID}'. Expected '${TARGET_TENANT_ID}'." >&2
  exit 1
fi

if [ "${EXPECTED_RUNTIME_SUBSCRIPTION_ID}" != "${TARGET_SUBSCRIPTION_ID}" ]; then
  echo "Out-of-policy EXPECTED_RUNTIME_SUBSCRIPTION_ID='${EXPECTED_RUNTIME_SUBSCRIPTION_ID}'. Expected '${TARGET_SUBSCRIPTION_ID}'." >&2
  exit 1
fi

if [ "${AZURE_TENANT_ID}" != "${TARGET_TENANT_ID}" ]; then
  echo "Out-of-policy AZURE_TENANT_ID='${AZURE_TENANT_ID}'. Expected '${TARGET_TENANT_ID}'." >&2
  exit 1
fi

if [ "${AZURE_SUBSCRIPTION_ID}" != "${TARGET_SUBSCRIPTION_ID}" ]; then
  echo "Out-of-policy AZURE_SUBSCRIPTION_ID='${AZURE_SUBSCRIPTION_ID}'. Expected '${TARGET_SUBSCRIPTION_ID}'." >&2
  exit 1
fi

required=(
  AZURE_CONTAINER_REGISTRY
  IMAGE_NAME
  AZURE_OPENAI_ENDPOINT
  AZURE_SEARCH_ENDPOINT
  PII_ENDPOINT
  PII_CONTAINER_ENDPOINT
  PGHOST
  EXPECTED_RUNTIME_ACCOUNT_UPN
  EXPECTED_RUNTIME_TENANT_ID
  EXPECTED_RUNTIME_SUBSCRIPTION_ID
  AZURE_TENANT_ID
  AZURE_SUBSCRIPTION_ID
)

for name in "${required[@]}"; do
  if [ -z "${!name:-}" ]; then
    echo "Missing required environment variable: ${name}" >&2
    exit 1
  fi
done

mkdir -p "${OUT_DIR}"

for manifest in namespace.yaml backend-service.yaml backend-configmap.yaml backend-deployment.yaml backend-ingress.yaml backend-networkpolicy.yaml backend-pdb.yaml; do
  src="${K8S_DIR}/${manifest}"
  [ -f "${src}" ] || continue
  envsubst < "${src}" > "${OUT_DIR}/${manifest}"
done

echo "Rendered manifests written to ${OUT_DIR}"
